repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.10.1'
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.9.0'
  hooks:
    - id: mypy
-   repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
    -   id: black
