repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.10.0'
  hooks:
    - id: mypy
      exclude: alembic
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        args: [--line-length=88]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        exclude: __init__.py
        args: [--max-line-length=88]
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
