"""Updated datatype for user phone column in all tables.

Revision ID: 06b59f5dd95e
Revises: 648c8318ea08
Create Date: 2024-04-29 11:54:03.067645
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06b59f5dd95e"
down_revision = "648c8318ea08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_attributes", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_flows", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_indicator_responses", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "phone",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "phone",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_indicator_responses", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_flows", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_attributes", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.alter_column(
            "user_phone",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
