"""Updated user activity model.

Revision ID: 7b2e93d16395
Revises: cf56b46971fa
Create Date: 2024-05-07 19:24:00.065218
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b2e93d16395"
down_revision = "cf56b46971fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.alter_column("is_started", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_succeeded", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_completed", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_activities", schema=None) as batch_op:
        batch_op.alter_column(
            "is_completed", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column(
            "is_succeeded", existing_type=sa.BOOLEAN(), nullable=False
        )
        batch_op.alter_column("is_started", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###
