"""User detail based tables.

Revision ID: 9a954f894483
Revises: 70bea50174bf
Create Date: 2024-04-22 10:43:30.711767
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a954f894483"
down_revision = "70bea50174bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("glific_user_id", sa.Integer(), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_phone", sa.String(length=50), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=True),
        sa.Column("field_value", sa.String(length=255), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_flows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_phone", sa.String(length=50), nullable=False),
        sa.Column("flow_uuid", sa.String(length=255), nullable=True),
        sa.Column("flow_name", sa.String(length=255), nullable=True),
        sa.Column("flow_type", sa.String(length=255), nullable=True),
        sa.Column("flow_run_status", sa.String(length=255), nullable=True),
        sa.Column("flow_start_time", sa.DateTime(), nullable=True),
        sa.Column("flow_end_time", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_flow_id", sa.Integer(), nullable=True),
        sa.Column("activity", sa.String(length=500), nullable=True),
        sa.Column("started", sa.Boolean(), nullable=True),
        sa.Column("started_on", sa.DateTime(), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=True),
        sa.Column("succeeded_on", sa.DateTime(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=True),
        sa.Column("completed_on", sa.DateTime(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_flow_id"],
            ["user_flows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_indicator_responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_flow_id", sa.Integer(), nullable=True),
        sa.Column("indicator_question", sa.String(length=255), nullable=True),
        sa.Column(
            "indicator_question_response", sa.String(length=255), nullable=True
        ),
        sa.Column("created_on", sa.DateTime(), nullable=True),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_flow_id"],
            ["user_flows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_indicator_responses")
    op.drop_table("user_activities")
    op.drop_table("user_flows")
    op.drop_table("user_attributes")
    op.drop_table("users")
    # ### end Alembic commands ###
