"""Adding index to the flou uuid cloumn in user flow table.

Revision ID: cf56b46971fa
Revises: 06b59f5dd95e
Create Date: 2024-05-03 15:19:29.399203
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cf56b46971fa"
down_revision = "06b59f5dd95e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_flows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_flows_flow_uuid"), ["flow_uuid"], unique=False
        )

    with op.batch_alter_table("user_indicator_responses", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
            autoincrement=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_indicator_responses", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            autoincrement=True,
        )

    with op.batch_alter_table("user_flows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_flows_flow_uuid"))

    # ### end Alembic commands ###
